//_ __ __ __ __ EditPlus_ _____ ____
//____ ___ ___ ____.
//____ ____ ____.

IDS_CLIENT_TIP_INC_000000
IDS_CLIENT_TIP_INC_000001
IDS_CLIENT_TIP_INC_000002
IDS_CLIENT_TIP_INC_000003
IDS_CLIENT_TIP_INC_000004
IDS_CLIENT_TIP_INC_000005
IDS_CLIENT_TIP_INC_000006
IDS_CLIENT_TIP_INC_000007
IDS_CLIENT_TIP_INC_000008
IDS_CLIENT_TIP_INC_000009
IDS_CLIENT_TIP_INC_000010
IDS_CLIENT_TIP_INC_000011
IDS_CLIENT_TIP_INC_000012
IDS_CLIENT_TIP_INC_000013
IDS_CLIENT_TIP_INC_000014

//______--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------